/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Forgot_Password_Frame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Forgot_Password_Frame.class.getName());
    
    private String UserId;
    
    // setter method
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }
    
    public String getUserId () {
        return this.UserId;
    }

    /**
     * Creates new form ha
     */
    public Forgot_Password_Frame() {
        initComponents();
        this.setLocationRelativeTo(null); // center your jFrame
        
        lblIncorrectQ1.setVisible(false);
        lblIncorrectQ2.setVisible(false);
        lblIdIncorrect.setVisible(false);
        
        IdVerifiesPanel.setVisible(true);
        safetyQuestionPanel.setVisible(false);
        resetPasswordPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        showSpace = new javax.swing.JPanel();
        IdVerifiesPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIdEnter = new javax.swing.JTextField();
        lblIdIncorrect = new javax.swing.JLabel();
        btnIdVerify = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReturnRequest = new javax.swing.JButton();
        safetyQuestionPanel = new javax.swing.JPanel();
        btnConSafety = new javax.swing.JButton();
        btnReturnSafety = new javax.swing.JButton();
        lblforgotQ1 = new javax.swing.JLabel();
        txtQ1 = new javax.swing.JTextField();
        lblIncorrectQ1 = new javax.swing.JLabel();
        lblforgotQ2 = new javax.swing.JLabel();
        txtQ2 = new javax.swing.JTextField();
        lblIncorrectQ2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resetPasswordPanel = new javax.swing.JPanel();
        btnA = new javax.swing.JButton();
        btnReturnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labelpassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        txtNewPasswordTest = new javax.swing.JPasswordField();
        lblTips = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(235, 245, 251));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgotPassword.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("ID Requested:");

        txtIdEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEnterActionPerformed(evt);
            }
        });

        lblIdIncorrect.setForeground(new java.awt.Color(255, 51, 51));
        lblIdIncorrect.setText("Hints");

        btnIdVerify.setBackground(new java.awt.Color(204, 255, 204));
        btnIdVerify.setText("ID Verify");
        btnIdVerify.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIdVerify.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIdVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdVerifyActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IdVerifyIcon1.png"))); // NOI18N

        btnReturnRequest.setBackground(new java.awt.Color(255, 153, 153));
        btnReturnRequest.setText("Return");
        btnReturnRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReturnRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReturnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IdVerifiesPanelLayout = new javax.swing.GroupLayout(IdVerifiesPanel);
        IdVerifiesPanel.setLayout(IdVerifiesPanelLayout);
        IdVerifiesPanelLayout.setHorizontalGroup(
            IdVerifiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdVerifiesPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(IdVerifiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IdVerifiesPanelLayout.createSequentialGroup()
                        .addGroup(IdVerifiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(IdVerifiesPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(IdVerifiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReturnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblIdIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(IdVerifiesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIdVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        IdVerifiesPanelLayout.setVerticalGroup(
            IdVerifiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdVerifiesPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdIncorrect)
                .addGap(24, 24, 24)
                .addGroup(IdVerifiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIdVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        safetyQuestionPanel.setForeground(new java.awt.Color(242, 242, 242));

        btnConSafety.setBackground(new java.awt.Color(204, 255, 204));
        btnConSafety.setText("Confirm");
        btnConSafety.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConSafety.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConSafety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConSafetyActionPerformed(evt);
            }
        });

        btnReturnSafety.setBackground(new java.awt.Color(255, 153, 153));
        btnReturnSafety.setText("Return");
        btnReturnSafety.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReturnSafety.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReturnSafety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnSafetyActionPerformed(evt);
            }
        });

        lblforgotQ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblforgotQ1.setText("Question 1");

        txtQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1ActionPerformed(evt);
            }
        });

        lblIncorrectQ1.setForeground(new java.awt.Color(255, 51, 51));
        lblIncorrectQ1.setText("Answer Incorrect, please try again");

        lblforgotQ2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblforgotQ2.setText("Question 2");

        lblIncorrectQ2.setForeground(new java.awt.Color(255, 51, 51));
        lblIncorrectQ2.setText("Answer Incorrect, please try again");

        lblName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblName.setText("Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Safety Question");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setText("Please answer these question to change your password.");

        javax.swing.GroupLayout safetyQuestionPanelLayout = new javax.swing.GroupLayout(safetyQuestionPanel);
        safetyQuestionPanel.setLayout(safetyQuestionPanelLayout);
        safetyQuestionPanelLayout.setHorizontalGroup(
            safetyQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(safetyQuestionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(safetyQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(safetyQuestionPanelLayout.createSequentialGroup()
                        .addComponent(btnReturnSafety, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnConSafety, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblforgotQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblforgotQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(safetyQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblIncorrectQ1)
                        .addComponent(txtQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(safetyQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblIncorrectQ2)
                        .addComponent(txtQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        safetyQuestionPanelLayout.setVerticalGroup(
            safetyQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, safetyQuestionPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(lblforgotQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncorrectQ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblforgotQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncorrectQ2)
                .addGap(36, 36, 36)
                .addGroup(safetyQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnSafety, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConSafety, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnA.setBackground(new java.awt.Color(204, 255, 204));
        btnA.setText("ID Verify");
        btnA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnReturnReset.setBackground(new java.awt.Color(255, 153, 153));
        btnReturnReset.setText("Return");
        btnReturnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReturnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReturnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Please Enter New Password");

        labelpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelpassword.setText("Please retype your new password");

        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });

        lblTips.setForeground(new java.awt.Color(255, 0, 0));
        lblTips.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTips.setText("tips");

        javax.swing.GroupLayout resetPasswordPanelLayout = new javax.swing.GroupLayout(resetPasswordPanel);
        resetPasswordPanel.setLayout(resetPasswordPanelLayout);
        resetPasswordPanelLayout.setHorizontalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTips, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                                .addComponent(btnReturnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNewPasswordTest, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resetPasswordPanelLayout.setVerticalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNewPasswordTest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTips, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout showSpaceLayout = new javax.swing.GroupLayout(showSpace);
        showSpace.setLayout(showSpaceLayout);
        showSpaceLayout.setHorizontalGroup(
            showSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resetPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showSpaceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(IdVerifiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(showSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showSpaceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(safetyQuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        showSpaceLayout.setVerticalGroup(
            showSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resetPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showSpaceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(IdVerifiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(showSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showSpaceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(safetyQuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
            .addComponent(showSpace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEnterActionPerformed

    private void btnIdVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdVerifyActionPerformed
        
        boolean IdStatus = false;
        boolean undoneSQ = false;
        String IdEntered = txtIdEnter.getText().trim();
        
        String QuesID1="";
        String QuesID2="";
        String Name;
        

        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", true);
        ArrayList<String[]> questionList = File_Control.readFile("securityQuestion.txt", true);
        
        for (String[] line : dataList){
            Name = line[2];
            QuesID1 = line[4];
            QuesID2 = line[6];
            if (IdEntered.equals(line[0]) && line[4].equals("-")) {
                undoneSQ = true;
                break;
            }
            else if(IdEntered.equals(line[0])){
                IdStatus = true;
                setUserId(line[0]);
                lblName.setText("Hi, " + Name + "!");
                break;
            }
            else{
               IdStatus = false;
            }
        }
        
        for (String[] line : questionList) {
            if (QuesID1.equals(line[0])) {
                lblforgotQ1.setText(line[1]);
            }
            else if (QuesID2.equals(line[0])) {
                lblforgotQ2.setText(line[1]);
            }
        }
        if (undoneSQ) {
            txtIdEnter.setText("");
            lblIdIncorrect.setVisible(true);
            lblIdIncorrect.setText("Your safety question has not been initialized yet.");
        }
        else if(IdStatus){
            safetyQuestionPanel.setVisible(true);
            IdVerifiesPanel.setVisible(false);
            resetPasswordPanel.setVisible(false);
            lblIdIncorrect.setVisible(false);
        }
        else{
            txtIdEnter.setText("");
            lblIdIncorrect.setVisible(true);
            lblIdIncorrect.setText("ID Incorrect, please try again");
        }
        
        
    }//GEN-LAST:event_btnIdVerifyActionPerformed

    private void btnReturnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnRequestActionPerformed
        Login_Frame Login_Frame = new Login_Frame();
        Login_Frame.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnReturnRequestActionPerformed

    private void btnConSafetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConSafetyActionPerformed
        
        String InputQ1 = txtQ1.getText();
        String InputQ2 = txtQ2.getText();
        boolean status = false;

        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", true);
        
        if (!InputQ1.isEmpty() && !InputQ2.isEmpty()) {
        for (String[] line : dataList){
            if (line[5].equals(InputQ1) && line[7].equals(InputQ2)){
            IdVerifiesPanel.setVisible(false);
            safetyQuestionPanel.setVisible(false);
            resetPasswordPanel.setVisible(true);
            lblIncorrectQ1.setVisible(false);
            lblIncorrectQ2.setVisible(false);
            lblTips.setText("");
            status = true;
            break;
            }
        }
        
        if (status == false) {
            txtQ1.setText("");
            txtQ2.setText("");
            lblIncorrectQ1.setVisible(true);
            lblIncorrectQ2.setVisible(true);
        }
        }
        else {
            JOptionPane.showMessageDialog(this, "Please don't leave any fields empty.");
        }
    }//GEN-LAST:event_btnConSafetyActionPerformed

//    void passwordValidation(){
        
//    }
    private void btnReturnSafetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSafetyActionPerformed
        IdVerifiesPanel.setVisible(true);
        safetyQuestionPanel.setVisible(false);
        resetPasswordPanel.setVisible(false);
    }//GEN-LAST:event_btnReturnSafetyActionPerformed

    private void txtQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ1ActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        String newPassword = txtNewPassword.getText().trim();
        String newPassword2 = txtNewPasswordTest.getText().trim();
        boolean status = false;
        boolean repeat = false;
        boolean empty = false;
        boolean same = false;

        if (newPassword.equals(newPassword2)){
            status = true;
        }
        else{
            same = true;
        }

        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", false);
        
        for (String[] line : dataList){
            if(line[0].equals(UserId) && !(line[3].equals(newPassword))){
                line[3] = newPassword;
            }
            else if(line[3].equals(newPassword)) {
                repeat = true;
            }
            else if(newPassword.isEmpty()){
                empty = true;
            }
        }
        
        if (repeat != true && empty != true && status == true && Validation.password(newPassword)){
            File_Control.writeFile("loginData.txt", dataList);
            JOptionPane.showMessageDialog(this, "Password Update successfully");
            Login_Frame Login_Frame = new Login_Frame();
            Login_Frame.setVisible(true);
            this.hide();
            
            
        }
        else if(empty == true){
            lblTips.setText("Please do not enter an empty password");
            txtNewPassword.setText("");
            txtNewPasswordTest.setText("");
        }
        else if(repeat == true){
            lblTips.setText("Don't enter the same password as old one.");
            txtNewPassword.setText("");
            txtNewPasswordTest.setText("");
            
        }
        else if (!Validation.password(newPassword)) {
            JOptionPane.showMessageDialog(this, "Password must contain at least 8 characters, uppercase, lowercase, number, and special character.");
            lblTips.setText("");
        }
        else if (same == true) {
            txtNewPassword.setText("");
            txtNewPasswordTest.setText("");
            lblTips.setText("Make sure the two entries are consistent.");
        }
        
        
    }//GEN-LAST:event_btnAActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void btnReturnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnResetActionPerformed
        IdVerifiesPanel.setVisible(false);
        safetyQuestionPanel.setVisible(true);
        resetPasswordPanel.setVisible(false);
    }//GEN-LAST:event_btnReturnResetActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Forgot_Password_Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IdVerifiesPanel;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnConSafety;
    private javax.swing.JButton btnIdVerify;
    private javax.swing.JButton btnReturnRequest;
    private javax.swing.JButton btnReturnReset;
    private javax.swing.JButton btnReturnSafety;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel lblIdIncorrect;
    private javax.swing.JLabel lblIncorrectQ1;
    private javax.swing.JLabel lblIncorrectQ2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTips;
    private javax.swing.JLabel lblforgotQ1;
    private javax.swing.JLabel lblforgotQ2;
    private javax.swing.JPanel resetPasswordPanel;
    private javax.swing.JPanel safetyQuestionPanel;
    private javax.swing.JPanel showSpace;
    private javax.swing.JTextField txtIdEnter;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtNewPasswordTest;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ2;
    // End of variables declaration//GEN-END:variables
}
