/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Cynthia
 */
public class Guest_Healthcare extends javax.swing.JFrame {
    public Guest_Healthcare() {
    initComponents();
    this.setLocationRelativeTo(null);
    cboProgram.setEnabled(false);
    jScrollPane9.getVerticalScrollBar().setUI(Utility_Methods.createWindowsScrollBarUI());
    jScrollPane9.getHorizontalScrollBar().setUI(Utility_Methods.createWindowsScrollBarUI());
    ChooseProgram1.setVisible(true);   
    ProgramDetails.setVisible(false); 
}
    
    
    public void modelComboBoxProgram() {
        ArrayList<String[]> dataList = File_Control.readFile("healthcareProgramData.txt", true);

        String category = cboCategory.getSelectedItem().toString();

        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();

        for (String[] list : dataList) {
            String programName = list[2];

            if (category.equals(list[1])) {
                comboModel.addElement(programName);
            }
        }
        cboProgram.setModel(comboModel);
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Support = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel302 = new javax.swing.JLabel();
        ChooseProgram1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ProgramDetails = new javax.swing.JPanel();
        jLabel250 = new javax.swing.JLabel();
        lblSpeaker = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        jLabel311 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblRegistered = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel251 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel255 = new javax.swing.JLabel();
        lblAvailableSpots = new javax.swing.JLabel();
        lblprogramName = new javax.swing.JLabel();
        txtSearchID = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        cboCategory = new javax.swing.JComboBox<>();
        cboProgram = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSpecialties_MainPage = new javax.swing.JButton();
        btnDoctor_MainPage = new javax.swing.JButton();
        btnBackToPatient_MainPage = new javax.swing.JButton();
        btnVisitorInformation_Specialties = new javax.swing.JButton();
        btnHealthcareProgram = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Support.setBackground(new java.awt.Color(30, 64, 175));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("🕓 Visiting Hours: 12:00 PM- 8:00 PM");

        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("📞 General Line: +603-8126 0888     🚑 Ambulance/ Emergency:  +603-8126 0999");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel92.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(0, 12, 102));
        jLabel92.setText("Healthcare Program & Registration ");
        jPanel9.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel93.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel93.setText("                  Join our community health programs designed to promote education, support, and lifestyle.");
        jPanel9.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 553, -1));

        jLabel94.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel94.setText("          Register for programs that fit your health goals and schedule.");
        jPanel9.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 30));

        jLabel168.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel9.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jLabel302.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel302.setText("Our Program");
        jPanel9.add(jLabel302, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 177, -1));

        ChooseProgram1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Healthcare.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Our Health, Our Priority");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Join the healthcare talk to learn useful tips, gain awareness, and");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("better understand how to care for your health and wellbeing.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        ChooseProgram1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 410, 230));

        jPanel9.add(ChooseProgram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 420, 240));

        ProgramDetails.setBackground(new java.awt.Color(255, 255, 255));

        jLabel250.setText("Dr.");

        lblSpeaker.setText("   ");

        lblLocation.setText("   ");

        jLabel311.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/healthcare1.png"))); // NOI18N
        jLabel311.setText("jLabel88");

        jLabel13.setText("👥");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(102, 104, 255));
        lblCategory.setText("     ");

        lblRegistered.setText(" ");

        btnRegister.setBackground(new java.awt.Color(37, 99, 235));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register for Program");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel15.setText("/");

        jLabel251.setText("📆");

        lblDate.setText("    ");

        jLabel253.setText("🕖");

        lblTime.setText("    ");

        jLabel16.setText("👤");

        jLabel255.setText("📍");

        lblAvailableSpots.setText("  ");

        lblprogramName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblprogramName.setText("  ");

        javax.swing.GroupLayout ProgramDetailsLayout = new javax.swing.GroupLayout(ProgramDetails);
        ProgramDetails.setLayout(ProgramDetailsLayout);
        ProgramDetailsLayout.setHorizontalGroup(
            ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblprogramName))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblCategory))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel311, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel251)
                .addGap(12, 12, 12)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel253)
                .addGap(12, 12, 12)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel255)
                .addGap(12, 12, 12)
                .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(jLabel250)
                .addGap(5, 5, 5)
                .addComponent(lblSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addComponent(lblRegistered)
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addGap(5, 5, 5)
                .addComponent(lblAvailableSpots))
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ProgramDetailsLayout.setVerticalGroup(
            ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgramDetailsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblprogramName)
                .addGap(6, 6, 6)
                .addComponent(lblCategory)
                .addGap(6, 6, 6)
                .addComponent(jLabel311)
                .addGap(18, 18, 18)
                .addGroup(ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel251)
                    .addComponent(lblDate))
                .addGap(6, 6, 6)
                .addGroup(ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel253)
                    .addComponent(lblTime))
                .addGap(7, 7, 7)
                .addGroup(ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel255)
                    .addComponent(lblLocation))
                .addGap(6, 6, 6)
                .addGroup(ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel250)
                    .addComponent(lblSpeaker))
                .addGap(6, 6, 6)
                .addGroup(ProgramDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblRegistered)
                    .addComponent(jLabel15)
                    .addComponent(lblAvailableSpots))
                .addGap(12, 12, 12)
                .addComponent(btnRegister)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane9.setViewportView(ProgramDetails);

        jPanel9.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 420, 240));

        txtSearchID.setText("🔍 Search Ticket ID");
        txtSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIDActionPerformed(evt);
            }
        });
        jPanel9.add(txtSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 180, 30));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "      ------ Category ------", "Education", "Support", "Lifestyle" }));
        cboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoryActionPerformed(evt);
            }
        });
        jPanel26.add(cboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, -1));

        cboProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "        ------ Program ------" }));
        cboProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProgramActionPerformed(evt);
            }
        });
        jPanel26.add(cboProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Select Category");
        jPanel26.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel95.setText("Select Program");
        jPanel26.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btnSearch.setBackground(new java.awt.Color(37, 99, 235));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel26.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Program.png"))); // NOI18N
        jPanel26.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 51));

        jPanel11.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 300, 230));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 310, 240));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 420, 240));

        btnSpecialties_MainPage.setBackground(new java.awt.Color(211, 211, 211));
        btnSpecialties_MainPage.setText("🏥 Specialties");
        btnSpecialties_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpecialties_MainPageActionPerformed(evt);
            }
        });
        jPanel9.add(btnSpecialties_MainPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnDoctor_MainPage.setBackground(new java.awt.Color(211, 211, 211));
        btnDoctor_MainPage.setText("👨 ‍Doctors");
        btnDoctor_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctor_MainPageActionPerformed(evt);
            }
        });
        jPanel9.add(btnDoctor_MainPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        btnBackToPatient_MainPage.setBackground(new java.awt.Color(211, 211, 211));
        btnBackToPatient_MainPage.setText("🔙");
        btnBackToPatient_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToPatient_MainPageActionPerformed(evt);
            }
        });
        jPanel9.add(btnBackToPatient_MainPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, -1));

        btnVisitorInformation_Specialties.setBackground(new java.awt.Color(211, 211, 211));
        btnVisitorInformation_Specialties.setText("👥 Visitor Information");
        btnVisitorInformation_Specialties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitorInformation_SpecialtiesActionPerformed(evt);
            }
        });
        jPanel9.add(btnVisitorInformation_Specialties, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        btnHealthcareProgram.setBackground(new java.awt.Color(211, 211, 211));
        btnHealthcareProgram.setText("📆 Healthcare Programs");
        btnHealthcareProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthcareProgramActionPerformed(evt);
            }
        });
        jPanel9.add(btnHealthcareProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 20, -1, -1));

        javax.swing.GroupLayout SupportLayout = new javax.swing.GroupLayout(Support);
        Support.setLayout(SupportLayout);
        SupportLayout.setHorizontalGroup(
            SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel91)
                .addGap(20, 20, 20))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        SupportLayout.setVerticalGroup(
            SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Support, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Support, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String selectedCategory = cboCategory.getSelectedItem().toString();
        String selectedProgram = cboProgram.getSelectedItem().toString();
        ArrayList<String[]> dataList = File_Control.readFile("healthcareProgramData.txt", true);

        if (!selectedCategory.equals("      ------ Category ------") && 
            !selectedProgram.equals("        ------ Program ------")) {

            ProgramDetails.setVisible(true);
            ChooseProgram1.setVisible(false);

            for (String[] program : dataList) {
                String category = program[1]; 
                String name = program[2]; 
                String date = program[3]; 
                String time = program[4]; 
                String location = program[5]; 
                String speaker = program[6];
                String totalCapacity = program[7]; 
                String registered = program[8];    

                if (selectedProgram.contains(name)) {  
                   lblprogramName.setText(name);
                   lblCategory.setText(category);
                   lblDate.setText(date);
                   lblTime.setText(time);
                   lblLocation.setText(location);
                   lblSpeaker.setText(speaker);
                   lblRegistered.setText(registered);
                   lblAvailableSpots.setText(totalCapacity);

                 
                   try {
                       int registeredCount = Integer.parseInt(registered);
                       int totalCapacityCount = Integer.parseInt(totalCapacity);

                       if (registeredCount >= totalCapacityCount) {
                           btnRegister.setEnabled(false);
                           btnRegister.setText("Program Full");
                           btnRegister.setBackground(Color.GRAY);
                       } else {
                           btnRegister.setEnabled(true);
                           btnRegister.setText("Register for Program");
                           btnRegister.setBackground(new Color(37, 99, 235));

                         
                           Guest_Register_Healthcare_Program guestRegisterHealthcareProgram = new Guest_Register_Healthcare_Program();
                           guestRegisterHealthcareProgram.setProgramData(

                               name,           
                               date,          
                               time,         
                               location,      
                               speaker,        
                               registered,     
                               totalCapacity 
                           );
                           guestRegisterHealthcareProgram.setVisible(true);
                           this.hide();
                       }
                   } catch (NumberFormatException ex) {
                       btnRegister.setEnabled(false);
                       btnRegister.setText("Registration Error");
                       btnRegister.setBackground(Color.ORANGE);
                   }
                   break;
                }
            }
        } else {
            
            ChooseProgram1.setVisible(true);
            ProgramDetails.setVisible(false);

            JOptionPane.showMessageDialog(this, 
                "Please select both a category and a program to view details.", 
                "Selection Required", 
                JOptionPane.INFORMATION_MESSAGE);
        }

                                  


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIDActionPerformed
        String searchTicketID = txtSearchID.getText().trim();

        if (searchTicketID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Ticket ID to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

       
        ArrayList<String[]> ticketDataList = File_Control.readFile("ticketData.txt", true);
        boolean ticketFound = false;

        for (String[] ticket : ticketDataList) {
            if (ticket[0].equals(searchTicketID)) {  // ticket[0] is the ticket ID
                ticketFound = true;

                
                String programID = ticket[1];
                ArrayList<String[]> programDataList = File_Control.readFile("healthcareProgramData.txt", true);

                for (String[] program : programDataList) {
                    if (program[0].equals(programID)) {  
                        String programName = program[2];  
                        String programDate = program[3];  
                        String programTime = program[4]; 
                        String programLocation = program[5];  

                    
                        JOptionPane.showMessageDialog(this,
                            "Ticket ID: " + searchTicketID +
                            "\nProgram: " + programName +
                            "\nDate: " + programDate +
                            "\nTime: " + programTime +
                            "\nLocation: " + programLocation ,
                            "Ticket Details",
                            JOptionPane.INFORMATION_MESSAGE);
                        break;
                    }
                }
                break;
            }
        }

        if (!ticketFound) {
            JOptionPane.showMessageDialog(this, 
                "Invalid Ticket ID: " + searchTicketID + 
                "\nPlease check your Ticket ID and try again.", 
                "Ticket Not Found", 
                JOptionPane.ERROR_MESSAGE);
        }
                                      
    }//GEN-LAST:event_txtSearchIDActionPerformed

    private void cboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoryActionPerformed
      
    String specialise = cboCategory.getSelectedItem().toString();
        
    if (specialise.equals("      ------ Category ------")) {
            cboProgram.setEnabled(false);
            cboProgram.setSelectedItem("        ------ Program ------");
        }
        
        else {
            modelComboBoxProgram();
            cboProgram.setEnabled(true);
        }    
    }//GEN-LAST:event_cboCategoryActionPerformed

    private void cboProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProgramActionPerformed

    }//GEN-LAST:event_cboProgramActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String selectedCategory = cboCategory.getSelectedItem().toString();
        String selectedProgram = cboProgram.getSelectedItem().toString();
        ArrayList<String[]> dataList = File_Control.readFile("healthcareProgramData.txt", true);

     
        if (!selectedCategory.equals("      ------ Category ------") && 
            !selectedProgram.equals("        ------ Program ------")) {

            // Show ProgramDetails panel, hide ChooseProgram panel
            ProgramDetails.setVisible(true);
            ChooseProgram1.setVisible(false);

            // Populate program details
            for (String[] program : dataList) {
                String category = program[1]; 
                String name = program[2]; 
                String date = program[3]; 
                String time = program[4]; 
                String location = program[5]; 
                String speaker = program[6];
                String totalCapacity = program[7]; 
                String registered = program[8];    

                if (selectedProgram.contains(name)) {  
                   lblprogramName.setText(name);
                   lblCategory.setText(category);
                   lblDate.setText(date);
                   lblTime.setText(time);
                   lblLocation.setText(location);
                   lblSpeaker.setText(speaker);
                   lblRegistered.setText(registered);
                   lblAvailableSpots.setText(totalCapacity);

                   // Display registered/total format
                   lblRegistered.setText(registered);
                   lblAvailableSpots.setText(totalCapacity);

                   
                   try {
                       int registeredCount = Integer.parseInt(registered);
                       int totalCapacityCount = Integer.parseInt(totalCapacity);

                       if (registeredCount >= totalCapacityCount) {
                           btnRegister.setEnabled(false);
                           btnRegister.setText("Program Full");
                           btnRegister.setBackground(Color.GRAY);
                       } else {
                           btnRegister.setEnabled(true);
                           btnRegister.setText("Register for Program");
                           btnRegister.setBackground(new Color(37, 99, 235));
                       }
                   } catch (NumberFormatException ex) {
                       // Handle case where values are not numbers
                       btnRegister.setEnabled(false);
                       btnRegister.setText("Registration Error");
                       btnRegister.setBackground(Color.ORANGE);
                   }
                }
            }
        } else {
           
            ChooseProgram1.setVisible(true);
            ProgramDetails.setVisible(false);

           
            JOptionPane.showMessageDialog(this, 
                "Please select both a category and a program to view details.", 
                "Selection Required", 
                JOptionPane.INFORMATION_MESSAGE);

    } 

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSpecialties_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialties_MainPageActionPerformed
        Guest_Main_Page guestmainPage = new Guest_Main_Page();
        guestmainPage.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSpecialties_MainPageActionPerformed

    private void btnDoctor_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctor_MainPageActionPerformed
        Guest_Doctor guestDoctor = new Guest_Doctor();
        guestDoctor.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnDoctor_MainPageActionPerformed

    private void btnBackToPatient_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToPatient_MainPageActionPerformed
        if (Main.getCurrentUserID() == null) {
            Login_Frame loginFrame = new Login_Frame();
            loginFrame.setVisible(true);
            this.hide();
        }
        else {
            Patient_Frame patientFrame = new Patient_Frame();
            patientFrame.setVisible(true);
            this.hide();
        }

    }//GEN-LAST:event_btnBackToPatient_MainPageActionPerformed

    private void btnVisitorInformation_SpecialtiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitorInformation_SpecialtiesActionPerformed
        Guest_Information guestInformation = new Guest_Information();
        guestInformation.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnVisitorInformation_SpecialtiesActionPerformed

    private void btnHealthcareProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthcareProgramActionPerformed
        Guest_Healthcare guestHealthcare = new Guest_Healthcare();
        guestHealthcare.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnHealthcareProgramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest_Healthcare().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChooseProgram1;
    private javax.swing.JPanel ProgramDetails;
    private javax.swing.JPanel Support;
    private javax.swing.JButton btnBackToPatient_MainPage;
    private javax.swing.JButton btnDoctor_MainPage;
    private javax.swing.JButton btnHealthcareProgram;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSpecialties_MainPage;
    private javax.swing.JButton btnVisitorInformation_Specialties;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JComboBox<String> cboProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAvailableSpots;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblRegistered;
    private javax.swing.JLabel lblSpeaker;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblprogramName;
    private javax.swing.JTextField txtSearchID;
    // End of variables declaration//GEN-END:variables
}