/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author teckann
 */
public class Login_Frame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Login_Frame.class.getName());

    /**
     * Creates new form Login_Frame
     */
    public Login_Frame() {
        initComponents();
        this.setLocationRelativeTo(null); // center jFrame
        
        lblWarning.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        divLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnContinueAsGuest = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblWarning = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        login_image = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Back");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel2.setText("Please Enter Account Details");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("User ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Password");

        btnLogin.setBackground(new java.awt.Color(174, 214, 241));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(209, 242, 235));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignUp.setText("Register Now");
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Don't have an account?");

        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Skip for now?");

        btnContinueAsGuest.setBackground(new java.awt.Color(209, 242, 235));
        btnContinueAsGuest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContinueAsGuest.setText("Continue As Guest");
        btnContinueAsGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContinueAsGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContinueAsGuestMouseExited(evt);
            }
        });
        btnContinueAsGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueAsGuestActionPerformed(evt);
            }
        });

        lblWarning.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 51, 51));
        lblWarning.setText("Incorrect User ID or Password!");

        lblForgotPassword.setForeground(new java.awt.Color(102, 153, 255));
        lblForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgotPassword.setText("Forgot Password");
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout divLoginLayout = new javax.swing.GroupLayout(divLogin);
        divLogin.setLayout(divLoginLayout);
        divLoginLayout.setHorizontalGroup(
            divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divLoginLayout.createSequentialGroup()
                .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divLoginLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnContinueAsGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(divLoginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(divLoginLayout.createSequentialGroup()
                                .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(divLoginLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUserID)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblForgotPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(11, 11, 11))
        );
        divLoginLayout.setVerticalGroup(
            divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(divLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinueAsGuest)
                    .addComponent(btnSignUp))
                .addGap(18, 18, 18))
        );

        login_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        login_image.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(divLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(login_image, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_image, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addComponent(divLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(133,193,233));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(174,214,241));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        // TODO add your handling code here:
        btnSignUp.setBackground(new Color(209,242,235));
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnContinueAsGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueAsGuestMouseExited
        // TODO add your handling code here:
        btnContinueAsGuest.setBackground(new Color(209,242,235));
    }//GEN-LAST:event_btnContinueAsGuestMouseExited

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        // TODO add your handling code here:
        btnSignUp.setBackground(new Color(160,220,210));
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnContinueAsGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueAsGuestMouseEntered
        // TODO add your handling code here:
        btnContinueAsGuest.setBackground(new Color(160,220,210));
    }//GEN-LAST:event_btnContinueAsGuestMouseEntered

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
        // TODO add your handling code here:
        Forgot_Password_Frame forgotPasswordFrame = new Forgot_Password_Frame();
        forgotPasswordFrame.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    private void lblForgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseExited
        // TODO add your handling code here:
        lblForgotPassword.setForeground(new Color(102,153,255));
    }//GEN-LAST:event_lblForgotPasswordMouseExited

    private void lblForgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseEntered
        // TODO add your handling code here:
        lblForgotPassword.setForeground(new Color(0,76,204));
    }//GEN-LAST:event_lblForgotPasswordMouseEntered

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", false);

        String inputUserID = txtUserID.getText().trim();
        String inputPassword = txtPassword.getText().trim();
        boolean status = false;
        
        // ArrayList = {{1,2,3},{4,5,6}}
        // Array = {1,2,3}
        
        String accountStatus="";
        for (String[] list : dataList) {
            String userID = list[0];
            String role = list[1];
            String userName = list[2];
            String userPassword = list[3];

            if (inputUserID.equals(userID) && inputPassword.equals(userPassword)) {
                accountStatus = list[list.length - 1];
                
                // "1" is active account ; "0" is deleted account
                if (accountStatus.equals("1")) {
                    status = true;
                    System.out.println("Successful Login.");
                    
                    switch (role) {
                        case "Admin" -> {
                            // set current user info
                            Main.setCurrentUserID(userID);
                            Main.setCurrentUserName(userName);
                            
                            System.out.println("Redirect to the Admin Frame.");
                            
                            // create new object for Admin_Frame & Admin_Frame2
                            Admin_Frame adminFrame = new Admin_Frame();
                            Admin_Frame2 adminFrame2 = new Admin_Frame2();
                            
                            // pass the Admin_Frame2 to Admin_Frame (by using setSecond_adminFrame method in Admin_Frame)
                            // so, I can get Admin_Frame2 from Admin_Frame
                            adminFrame.setSecond_adminFrame(adminFrame2);
                            // pass the Admin_Frame to Admin_Frame2 (by using setFirst_adminFrame method in Admin_Frame2)
                            // can get Admin_Frame from Admin_Frame2
                            adminFrame2.setFirst_adminFrame(adminFrame);
                            
                            // the first frame after login will be Admin_Frame
                            // show the adminFrame & the first panel will be Admin Welcome
                            adminFrame.setVisible(true);
                            adminFrame.showPanel("Admin Welcome");
                            this.hide(); // hide this login panel
                        }
                        
                        case "Doctor" -> {
                            System.out.println("Doctor Role");
                            Main.setCurrentUserID(userID);
                            Main.setCurrentUserName(userName);
                            Doctor_Frame doctorFrame = new Doctor_Frame();
                            doctorFrame.setVisible(true);
                            this.hide();
                        }
                        
                        case "Patient" -> {
                            Main.setCurrentUserID(userID);
                            Main.setCurrentUserName(userName);


                            Patient_Frame patientFrame = new Patient_Frame();
                            patientFrame.setVisible(true);
                            this.hide();
                            System.out.println("Patient Role");
                        }
                        
                        default -> {}
                    }
                    break;
                }
            }
        }

        if (!status) {
            txtUserID.setText("");
            txtPassword.setText("");
            
            if (accountStatus.equals("0")) {
                lblWarning.setText("This account has been suspended. Contact admin to reactive.");
                System.out.println("Deleted Account.");
            }
            
            else {
                lblWarning.setText("Incorrect User ID or Password! Please Try Again.");
                System.out.println("Incorrect User ID or Password.");
            }
        }
    }// GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        Register_Frame registerFrame = new Register_Frame();
        registerFrame.setVisible(true);
        this.hide();
    }// GEN-LAST:event_btnSignUpActionPerformed

    private void btnContinueAsGuestActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnContinueAsGuestActionPerformed
        // TODO add your handling code here:
        Main.setCurrentUserID(null); // prevent different role enter as patient accidentally
        Guest_Main_Page guestMainPage = new Guest_Main_Page();
        guestMainPage.setVisible(true);
        this.hide();
    }// GEN-LAST:event_btnContinueAsGuestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login_Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinueAsGuest;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel divLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JLabel login_image;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
