/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teckann
 */
public final class Suspended_Account extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Suspended_Account.class.getName());
    
    private final String defaultText = "N/A";

    /**
     * Creates new form Suspended_Account
     */
    public Suspended_Account() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tblSuspendedAccount.setEnabled(false);
        lblWarning.setText("");
        updatePasswordTable();
        modelComboBoxSuspendedUserID();
        
        setDefaultText();
        cboSuspendedUserID.setSelectedItem(" - Please Select - ");  
    }
    
    public void updatePasswordTable() {
        String[] tableTitle = {"User ID", "User Role", "User Name"};
        
        // readFile method will return an ArrayList
        // create an ArrayList to store it
        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", false);
        
        // Model table - clear the table
        // it will only display the data that we add below
        DefaultTableModel tableModel = new DefaultTableModel();
        
        tableModel.setColumnIdentifiers(tableTitle);

        for (String[] list : dataList) {
            if (list[list.length - 1].equals("0")) {
                tableModel.addRow(list);
            }
        }
        tblSuspendedAccount.setModel(tableModel);
    }
    
    public void modelComboBoxSuspendedUserID() {
        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", false);

        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
        
        comboModel.addElement(" - Please Select - ");
        for (String[] list : dataList) {
            if (list[list.length - 1].equals("0")) {
                comboModel.addElement(list[0]);
            }
        }

        cboSuspendedUserID.setModel(comboModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSuspendedAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboSuspendedUserID = new javax.swing.JComboBox<>();
        btnReactive = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(235, 245, 251));

        tblSuspendedAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSuspendedAccount.setRowHeight(30);
        tblSuspendedAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuspendedAccountMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblSuspendedAccount);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suspended User ID");

        cboSuspendedUserID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSuspendedUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSuspendedUserIDActionPerformed(evt);
            }
        });

        btnReactive.setBackground(new java.awt.Color(204, 255, 204));
        btnReactive.setText("Reactive");
        btnReactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactiveActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(235, 245, 251));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("User ID");

        jLabel3.setText("User Name");

        jLabel4.setText("Role");

        jLabel5.setText(":");

        jLabel6.setText(":");

        jLabel7.setText(":");

        lblUserID.setText("N/A");

        lblUserName.setText("N/A");

        lblRole.setText("N/A");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(lblUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(lblUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lblRole))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblWarning.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 51, 51));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarning.setText("Please Select Correct Suspended User ID.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboSuspendedUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnReactive, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboSuspendedUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReactive, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSuspendedAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuspendedAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSuspendedAccountMouseClicked

    private void btnReactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactiveActionPerformed
        // TODO add your handling code here:
        String activeID = cboSuspendedUserID.getSelectedItem().toString();
        
        ArrayList<String[]> loginDataList = File_Control.readFile("loginData.txt", false);
        ArrayList<String[]> adminDataList = File_Control.readFile("adminData.txt", false);
        ArrayList<String[]> doctorDataList = File_Control.readFile("doctorData.txt", false);
        ArrayList<String[]> patientDataList = File_Control.readFile("patientData.txt", false);
        
        boolean loginFileStatus = false;
        boolean roleFileStatus = false;
        
        for (String[] list : loginDataList) {
            String UserID = list[0];

            if (UserID.equals(activeID)) {
                list[list.length - 1] = "1";
                loginFileStatus = true;
                break;
            }
        }
        
        if (activeID.equals(" - Please Select - ")) {
            lblWarning.setText("Please Select Correct Suspended User ID.");
        }

        else if (activeID.startsWith("A")) {
            for (String[] list : adminDataList) {
                String UserID = list[0];

                if (UserID.equals(activeID)) {
                    list[list.length - 1] = "1";
                    roleFileStatus = true;
                    break;
                }
            }
        }

        else if (activeID.startsWith("D")) {
            for (String[] list : doctorDataList) {
                String UserID = list[0];

                if (UserID.equals(activeID)) {
                    list[list.length - 1] = "1";
                    roleFileStatus = true;
                    break;
                }
            }
        }

        else if (activeID.startsWith("P")) {
            for (String[] list : patientDataList) {
                String UserID = list[0];

                if (UserID.equals(activeID)) {
                    list[list.length - 1] = "1";
                    roleFileStatus = true;
                    break;
                }
            }
        }
        
        // check either all the processes are passed
        if (loginFileStatus == true && roleFileStatus == true) {
            // start writing file
            File_Control.writeFile("loginData.txt", loginDataList);
            
            // write file based on the role
            if (activeID.startsWith("A")) {
                File_Control.writeFile("adminData.txt", adminDataList);
            }
            else if (activeID.startsWith("D")) {
                File_Control.writeFile("doctorData.txt", doctorDataList);
            }
            else if (activeID.startsWith("P")) {
                File_Control.writeFile("patientData.txt", patientDataList);
            }
            
            updatePasswordTable();
            modelComboBoxSuspendedUserID();
        } 
    }//GEN-LAST:event_btnReactiveActionPerformed

    private void cboSuspendedUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSuspendedUserIDActionPerformed
        // TODO add your handling code here:
        String activeID = cboSuspendedUserID.getSelectedItem().toString();
        ArrayList<String[]> dataList = File_Control.readFile("loginData.txt", false);
        
        for (String[] list : dataList) {
            if (activeID.equals(list[0])) {
                lblUserID.setText(list[0]);
                lblUserName.setText(list[2]);
                lblRole.setText(list[1]);
                
                break;
            }
            setDefaultText();
        }
    }//GEN-LAST:event_cboSuspendedUserIDActionPerformed
    
    public void setDefaultText() {
        lblUserID.setText(defaultText);
        lblUserName.setText(defaultText);
        lblRole.setText(defaultText);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Suspended_Account().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReactive;
    private javax.swing.JComboBox<String> cboSuspendedUserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTable tblSuspendedAccount;
    // End of variables declaration//GEN-END:variables
}
